SAP/ui5-project

- package.json
See https://github.com/SAP/ui5-fs/pull/24 for details
> [INTERNAL] package.json: Define files to publish 

- lib/projectPreprocessor.js
- test/lib/projectPreprocessor.js
> [FEATURE] projectPreprocessor: Allow application project dependency on non-root level

- lib/translators/npm.js
- test/fixtures/application.g/node_modules/library.d/main/src/library/d/.library
- test/fixtures/application.g/node_modules/library.d/main/src/library/d/some.js
- test/fixtures/application.g/node_modules/library.d/package.json
- test/fixtures/application.g/node_modules/library.d/ui5.yaml
- test/fixtures/application.g/package.json
- test/lib/translators/npm.js
> [FIX] npm t8r: Again, handle npm optionalDependencies correctly

- docs/Configuration.md
> [INTERNAL] Docs: Fix link to types

- package-lock.json
- package.json
- test/lib/extensions.js
- test/lib/projectPreprocessor.js
Depends on https://github.com/SAP/ui5-builder/pull/263
> [INTERNAL] Tests: Fix errors due to new namespace detection of LibraryFormatter

- lib/projectPreprocessor.js
- package-lock.json
- package.json
- test/fixtures/application.a/middleware.a.js
- test/lib/extensions.js
As per RFC 0005: https://github.com/SAP/ui5-tooling/pull/151
> [FEATURE] projectPreprocessor: Add handling for server-middleware extensions

- lib/projectPreprocessor.js
- test/lib/projectPreprocessor.js
> [INTERNAL] Do not log deprecated and internal warnings for deeply nested dependencies

- lib/ui5Framework/AbstractResolver.js
- test/lib/ui5framework/AbstractResolver.js
> [INTERNAL] AbstractResolver: Resolve cwd / ui5HomeDir paths

- lib/translators/ui5Framework.js
- lib/ui5Framework/npm/Registry.js
- test/lib/translators/ui5Framework.integration.js
Registry 404 errors should include package version
> [INTERNAL] ui5Framework: Improve error handling and logging

- lib/projectPreprocessor.js
- lib/translators/ui5Framework.js
- test/lib/extensions.js
- test/lib/projectPreprocessor.js
- test/lib/translators/ui5Framework.integration.js
Alternative to (_level === 0) checks.
> [INTERNAL] projectPreprocessor: Add _isRoot flag to root project

- lib/projectPreprocessor.js
- lib/ui5Framework/AbstractResolver.js
- [INTERNAL] Project shims: Fix error message for missing configuration
- [INTERNAL] ui5Framework.AbstractResolver: Enhance install example for full use case
> [INTERNAL] Fix project shim error message and enhance framework resolver example

- index.js
- lib/projectPreprocessor.js
- package-lock.json
- package.json
- test/lib/extensions.js
- test/lib/index.js
Depends on:
- taskRepository refactoring: https://github.com/SAP/ui5-builder/pull/438
- middlewareRepository refactoring: https://github.com/SAP/ui5-server/pull/302
Also implements:
- Lazy index.js requires
> [INTERNAL] Adopt to task- and middlewareRepository refactorings

- lib/translators/ui5Framework.js
- test/lib/translators/ui5Framework.js
Resolve "latest" to latest version.
> [FIX] ui5Framework t8r: Resolve versionOverride string

- lib/validation/schema/specVersion/2.0.json
- lib/validation/schema/specVersion/2.0/kind/extension.json
- lib/validation/schema/specVersion/2.0/kind/extension/project-shim.json
- lib/validation/schema/specVersion/2.0/kind/extension/server-middleware.json
- lib/validation/schema/specVersion/2.0/kind/extension/task.json
- lib/validation/schema/specVersion/2.0/kind/project.json
- lib/validation/schema/specVersion/2.0/kind/project/application.json
- lib/validation/schema/specVersion/2.0/kind/project/library.json
- lib/validation/schema/specVersion/2.0/kind/project/module.json
- lib/validation/schema/specVersion/2.0/kind/project/theme-library.json
- lib/validation/schema/ui5.json
- test/lib/validation/ValidationError.js
- test/lib/validation/schema/specVersion/2.0/kind/project.js
- test/lib/validation/schema/specVersion/2.0/kind/project/application.js
- test/lib/validation/schema/specVersion/2.0/kind/project/library.js
- test/lib/validation/schema/specVersion/2.0/kind/project/module.js
- test/lib/validation/schema/specVersion/2.0/kind/project/theme-library.js
- test/lib/validation/schema/ui5.js
Also refactored the schema to only test and validate the metadata where
required.
> [FIX] Schema: Add missing metadata properties

- lib/ui5Framework/Sapui5Resolver.js
- test/lib/ui5framework/Sapui5Resolver.js
> [INTERNAL] Document 1.77 workaround

- lib/translators/ui5Framework.js
- test/lib/translators/ui5Framework.js
> [FIX] ui5Framework.mergeTrees: Do not abort merge if a project has already been processed

- lib/validation/schema/specVersion/2.0/kind/project.json
- test/lib/validation/schema/specVersion/2.0/kind/project/application.js
- test/lib/validation/schema/specVersion/2.0/kind/project/library.js
> [FIX] Schema: Add missing bundle section "name"

- lib/validation/validator.js
- Only require modules / dependencies when needed
- Create singleton validator instance only on first usage
> [PERF] validator: Lazy load dependencies

- lib/projectPreprocessor.js
- lib/translators/ui5Framework.js
- lib/validation/schema/specVersion/2.0.json
- lib/validation/schema/specVersion/2.0/kind/extension.json
- lib/validation/schema/specVersion/2.0/kind/extension/project-shim.json
- lib/validation/schema/specVersion/2.0/kind/extension/server-middleware.json
- lib/validation/schema/specVersion/2.0/kind/extension/task.json
- lib/validation/schema/specVersion/2.0/kind/project.json
- lib/validation/schema/specVersion/2.0/kind/project/application.json
- lib/validation/schema/specVersion/2.0/kind/project/library.json
- lib/validation/schema/specVersion/2.0/kind/project/module.json
- lib/validation/schema/specVersion/2.0/kind/project/theme-library.json
- lib/validation/schema/ui5.json
- test/lib/extensions.js
- test/lib/projectPreprocessor.js
- test/lib/validation/schema/__helper__/customConfiguration.js
- test/lib/validation/schema/__helper__/extension.js
- test/lib/validation/schema/__helper__/framework.js
- test/lib/validation/schema/__helper__/project.js
- test/lib/validation/schema/specVersion/2.0/kind/extension.js
- test/lib/validation/schema/specVersion/2.0/kind/extension/project-shim.js
- test/lib/validation/schema/specVersion/2.0/kind/extension/server-middleware.js
- test/lib/validation/schema/specVersion/2.0/kind/extension/task.js
- test/lib/validation/schema/specVersion/2.0/kind/project.js
- test/lib/validation/schema/specVersion/2.0/kind/project/application.js
- test/lib/validation/schema/specVersion/2.0/kind/project/library.js
- test/lib/validation/schema/specVersion/2.0/kind/project/module.js
- test/lib/validation/schema/specVersion/2.0/kind/project/theme-library.js
- test/lib/validation/schema/ui5.js
- Adds libraryPreload/componentPreload excludes configuration
JIRA: CPOUI5FOUNDATION-233
> [FEATURE] specVersion 2.3

- lib/projectPreprocessor.js
- lib/translators/ui5Framework.js
- lib/validation/schema/specVersion/2.0.json
- lib/validation/schema/specVersion/2.0/kind/extension.json
- lib/validation/schema/specVersion/2.0/kind/extension/project-shim.json
- lib/validation/schema/specVersion/2.0/kind/extension/server-middleware.json
- lib/validation/schema/specVersion/2.0/kind/extension/task.json
- lib/validation/schema/specVersion/2.0/kind/project.json
- lib/validation/schema/specVersion/2.0/kind/project/application.json
- lib/validation/schema/specVersion/2.0/kind/project/library.json
- lib/validation/schema/specVersion/2.0/kind/project/module.json
- lib/validation/schema/specVersion/2.0/kind/project/theme-library.json
- lib/validation/schema/ui5.json
- test/lib/extensions.js
- test/lib/projectPreprocessor.js
- test/lib/validation/schema/__helper__/customConfiguration.js
- test/lib/validation/schema/__helper__/extension.js
- test/lib/validation/schema/__helper__/framework.js
- test/lib/validation/schema/__helper__/project.js
- test/lib/validation/schema/specVersion/2.0/kind/extension.js
- test/lib/validation/schema/specVersion/2.0/kind/extension/project-shim.js
- test/lib/validation/schema/specVersion/2.0/kind/project/application.js
- test/lib/validation/schema/specVersion/2.0/kind/project/library.js
- test/lib/validation/schema/specVersion/2.0/kind/project/module.js
- test/lib/validation/schema/specVersion/2.0/kind/project/theme-library.js
- test/lib/validation/schema/ui5.js
- Adds new bundle section mode "bundleInfo"
JIRA: CPOUI5FOUNDATION-141
> [FEATURE] specVersion 2.4

- lib/projectPreprocessor.js
- lib/translators/ui5Framework.js
- lib/validation/schema/specVersion/2.0.json
- lib/validation/schema/specVersion/2.0/kind/extension.json
- lib/validation/schema/specVersion/2.0/kind/extension/project-shim.json
- lib/validation/schema/specVersion/2.0/kind/extension/server-middleware.json
- lib/validation/schema/specVersion/2.0/kind/extension/task.json
- lib/validation/schema/specVersion/2.0/kind/project.json
- lib/validation/schema/specVersion/2.0/kind/project/application.json
- lib/validation/schema/specVersion/2.0/kind/project/library.json
- lib/validation/schema/specVersion/2.0/kind/project/module.json
- lib/validation/schema/specVersion/2.0/kind/project/theme-library.json
- lib/validation/schema/ui5.json
- test/lib/extensions.js
- test/lib/projectPreprocessor.js
- test/lib/validation/schema/__helper__/customConfiguration.js
- test/lib/validation/schema/__helper__/extension.js
- test/lib/validation/schema/__helper__/framework.js
- test/lib/validation/schema/__helper__/project.js
- test/lib/validation/schema/specVersion/2.0/kind/extension.js
- test/lib/validation/schema/specVersion/2.0/kind/extension/project-shim.js
- test/lib/validation/schema/specVersion/2.0/kind/project/application.js
- test/lib/validation/schema/specVersion/2.0/kind/project/library.js
- test/lib/validation/schema/specVersion/2.0/kind/project/module.js
- test/lib/validation/schema/specVersion/2.0/kind/project/theme-library.js
- test/lib/validation/schema/ui5.js
Adds support for build configuration includeDependency
JIRA: CPOUI5FOUNDATION-208
> [FEATURE] specVersion 2.5

- lib/build/ProjectBuilder.js
- lib/graph/Module.js
- lib/specifications/ComponentProject.js
- lib/specifications/Project.js
- lib/specifications/types/Module.js
- lib/specifications/types/ThemeLibrary.js
- test/lib/build/ProjectBuilder.js
- test/lib/build/helpers/createBuildManifest.integration.js
- test/lib/graph/Module.js
- test/lib/specifications/types/Application.js
- test/lib/specifications/types/Library.js
- test/lib/specifications/types/Module.js
- test/lib/specifications/types/ThemeLibrary.js
By using new factory API from https://github.com/SAP/ui5-fs/pull/438
> [INTERNAL] Specifications: Make getReader/getWorkspace synchronous

- lib/build/TaskRunner.js
- lib/build/helpers/ProjectBuildContext.js
- lib/build/helpers/TaskUtil.js
- lib/graph/ProjectGraph.js
- lib/graph/projectGraphBuilder.js
- lib/specifications/ComponentProject.js
- lib/specifications/Project.js
- lib/specifications/Specification.js
- lib/specifications/types/Application.js
- lib/specifications/types/Library.js
- lib/specifications/types/Module.js
- lib/specifications/types/ThemeLibrary.js
- test/lib/build/TaskRunner.js
- test/lib/build/helpers/ProjectBuildContext.js
- test/lib/build/helpers/TaskUtil.js
New API is only available to custom tasks defining specVerson 3.0 and
later.
> [FEATURE] TaskUtil: Enhance interface provided to custom tasks defining specVersion 3.0 and later

- package.json
This reverts commit 47ba17a231c2ccf0967af705ea914e2c4cd7316b.
> Revert "[INTERNAL] package.json: Change pre-release identifier to 'rc'"

- lib/specifications/Specification.js
- test/lib/specifications/Specification.js
Depends on https://github.com/SAP/ui5-fs/pull/463
> [INTERNAL] Specification#getRootReader: Use .gitignore excludes by default

- lib/build/ProjectBuilder.js
- lib/build/TaskRunner.js
- lib/build/helpers/ProjectBuildContext.js
- package-lock.json
- package.json
- test/lib/build/ProjectBuilder.js
- test/lib/build/TaskRunner.js
- test/lib/build/helpers/ProjectBuildContext.js
Depends on https://github.com/SAP/ui5-logger/pull/363
JIRA: CPOUI5FOUNDATION-603
> [INTERNAL] Enhance logging based on new ui5-logger

- lib/specifications/types/Application.js
- lib/specifications/types/Library.js
- lib/specifications/types/Module.js
- lib/specifications/types/ThemeLibrary.js
- test/lib/specifications/types/Application.js
- test/lib/specifications/types/Library.js
- test/lib/specifications/types/Module.js
- test/lib/specifications/types/ThemeLibrary.js
Otherwise they can get mixed up with another project's log output
> [INTERNAL] Specifications: Ensure path-mapping log messages are written synchronously per project

- lib/graph/Workspace.js
- test/lib/graph/helpers/createWorkspace.js
> [INTERNAL] Workspace: Minor cleanups

- lib/graph/Module.js
- lib/specifications/Specification.js
- package-lock.json
- package.json
- test/lib/build/ProjectBuilder.js
- test/lib/graph/Module.js
- test/lib/graph/graphFromObject.js
- test/lib/specifications/Specification.js
- test/lib/specifications/types/Module.js
- test/lib/validation/schema/specVersion/kind/project/application.js
This path will be used as the base for many operations. We should ensure
it is absolute not to get surprised.
Test changes depend on https://github.com/SAP/ui5-fs/pull/481
> [INTERNAL] Module/Specification: Ensure modulePath is absolute

- lib/validation/validator.js
- test/lib/validation/validator.js
Validate schemaName properly based on the enum by fixing a typo in tests & correcting the logical expression
> [FIX] Validator constructor checks

- lib/graph/helpers/ui5Framework.js
- test/lib/graph/helpers/ui5Framework.js
Fixes: https://github.com/SAP/ui5-tooling/issues/780
> [FIX] ui5Framework: Improve error handling for duplicate lib declaration

- lib/config/Configuration.js
- lib/ui5Framework/Sapui5MavenSnapshotResolver.js
- lib/ui5Framework/maven/Installer.js
- lib/ui5Framework/maven/Registry.js
- test/lib/config/Configuration.js
- test/lib/graph/helpers/ui5Framework.integration.js
- test/lib/ui5framework/Sapui5MavenSnapshotResolver.js
- test/lib/ui5framework/maven/Installer.js
- test/lib/ui5framework/maven/Registry.js
- test/lib/utils/fs.js
Enhance code coverage across related modules and apply minor corrections
JIRA: CPOUI5FOUNDATION-634
> [INTERNAL] Sapui5MavenSnapshotResolver: Integrate config/Configuration

- lib/config/Configuration.js
- lib/ui5Framework/Sapui5MavenSnapshotResolver.js
- test/lib/config/Configuration.js
- test/lib/ui5framework/Sapui5MavenSnapshotResolver.js
> [FIX] Configuration: Rename toJSON => toJson

- test/lib/specifications/types/Application.js
- test/lib/specifications/types/Library.js
- test/lib/specifications/types/Module.js
- test/lib/specifications/types/ThemeLibrary.js
Add tests showing the issue reported in https://github.com/SAP/ui5-tooling/issues/826
> [INTERNAL] Specification: Add tests for resource excludes with absolute paths

- lib/graph/ProjectGraph.js
- lib/graph/providers/NodePackageDependencies.js
- test/lib/graph/ProjectGraph.js
- test/lib/graph/projectGraphBuilder.js
- test/lib/graph/providers/NodePackageDependencies.js
Resolves https://github.com/SAP/ui5-tooling/issues/862
> [FIX] NodePackageDependencies: Implement validation for missing package.json attributes

- lib/specifications/types/Application.js
- test/lib/specifications/types/Application.js
Fixes: https://github.com/SAP/ui5-tooling/issues/306
> [FIX] application: Improve error message for missing manifest.json

- lib/ui5Framework/Sapui5MavenSnapshotResolver.js
JIRA: CPOUI5FOUNDATION-802
We have decided to postpone this removal for v5.0
> [INTERNAL] Move TODOs for 5.0

- package-lock.json
- package.json
Cherry-pick of https://github.com/SAP/ui5-project/pull/720
> [DEPENDENCY] Bump pacote from 17.0.7 to 18.0.6

- lib/validation/schema/specVersion/kind/project.json
- test/lib/validation/schema/specVersion/kind/project/application.js
- test/lib/validation/schema/specVersion/kind/project/library.js
JIRA: CPOUI5FOUNDATION-835
This change addresses the commnents in https://github.com/SAP/ui5-project/pull/731
> [INTERNAL] Determine correctly mode=require sections and restrict the async flag
