- lib/translators/npm.js
- test/fixtures/err.application.a/package.json
- test/lib/translators/npm.js
If the dependency resolution falls back to try resolving via a
collection it looks for a package.json in the path above the current
module. The current implementation throws when no package.json could be
found at all.
> [FIX] npm t8r: Fix collection fallback with missing package.json

- lib/translators/npm.js
Fixes https://github.com/SAP/ui5-project/issues/14 .
> npm translator: Fix endless loop in case of dependency cycles

- lib/projectPreprocessor.js
- package-lock.json
- package.json
- test/fixtures/legacy.collection.a/src/legacy.library.x/node_modules/library.f/package.json
- test/fixtures/legacy.collection.a/src/legacy.library.x/node_modules/library.f/ui5.yaml
- test/fixtures/legacy.collection.a/src/legacy.library.x/package.json
- test/fixtures/legacy.collection.a/src/legacy.library.x/src/legacy/library/x/.library
- test/fixtures/legacy.collection.a/src/legacy.library.x/src/legacy/library/x/some.js
- test/fixtures/legacy.collection.a/src/legacy.library.y/node_modules/library.f/package.json
- test/fixtures/legacy.collection.a/src/legacy.library.y/node_modules/library.f/ui5.yaml
- test/fixtures/legacy.collection.a/src/legacy.library.y/package.json
- test/fixtures/legacy.collection.a/src/legacy.library.y/src/legacy/library/y/.library
- test/fixtures/legacy.collection.a/src/legacy.library.y/src/legacy/library/y/some.js
- test/fixtures/legacy.library.a/node_modules/library.f/package.json
- test/fixtures/legacy.library.a/node_modules/library.f/ui5.yaml
- test/fixtures/legacy.library.a/package.json
- test/fixtures/legacy.library.a/src/legacy/library/a/.library
- test/fixtures/legacy.library.a/src/legacy/library/a/some.js
- test/fixtures/legacy.library.b/node_modules/library.f/package.json
- test/fixtures/legacy.library.b/node_modules/library.f/ui5.yaml
- test/fixtures/legacy.library.b/package.json
- test/fixtures/legacy.library.b/src/legacy/library/b/.library
- test/fixtures/legacy.library.b/src/legacy/library/b/some.js
- test/lib/extensions.js
- test/lib/projectPreprocessor.js
Identify and apply extensions in dependency tree so that they can influence the processing of a project.
Implements foundation for "extensions" as required in [**RFC 0001** (Type Extensibility)](https://github.com/SAP/ui5-tooling/blob/rfc-type-ext/rfcs/0001-type-extensibility.md) and [**RFC 0004** (Simple Build Extensibility)](https://github.com/SAP/ui5-tooling/blob/rfc-simple-build-extensibility/rfcs/0004-simple-build-extensibility.md)
Implements shim extensions as defined in [**RFC 0002** (Project Shims)](https://github.com/SAP/ui5-tooling/blob/rfc-project-shims/rfcs/0002-project-shims.md)
> [INTERNAL] Extension handling groundwork

- lib/translators/npm.js
- test/fixtures/application.g/package.json
- test/fixtures/application.g/ui5.yaml
- test/fixtures/application.g/webapp/manifest.json
- test/lib/translators/npm.js
In the past, optionalDependencies that could not be located caused a
"Failed to locate module".
Fixes #51
> [FIX] npm t8r: Handle npm optionalDependencies correctly

- lib/projectPreprocessor.js
- test/fixtures/application.a/task.a.js
- test/lib/extensions.js
As per RFC0004: https://github.com/SAP/ui5-tooling/pull/54
> [FEATURE] projectPreprocessor: Add handling for task extensions

- README.md
- docs/BuildExtensibility.md
Related to https://github.com/SAP/ui5-tooling/pull/54#issuecomment-439617815
> Add documentation about Build Extensibility

- .eslintrc.js
- docs/BuildExtensibility.md
- index.js
- jsdoc.json
- lib/normalizer.js
- lib/projectPreprocessor.js
- lib/translators/npm.js
- lib/translators/static.js
- package-lock.json
- package.json
Also:
- prevent use of unkown tags
- add some docdash specific page options
> [INTERNAL] JSDoc: Make API private by default

- README.md
- lib/normalizer.js
- lib/translators/static.js
- test/lib/normalizer.js
This should future-proof the normalizer API to allow for eventually passing
translator objects/instances instead of a simple string.
BREAKING CHANGE: Renamed parameter "translator" of functions generateDependencyTree and generateProjectTree to "translatorName"
Downstream adaptions: https://github.com/SAP/ui5-cli/pull/112
> [BREAKING] normalizer: Rename optional parameter "translator" 

- lib/projectPreprocessor.js
- test/lib/extensions.js
- test/lib/projectPreprocessor.js
Old CLI releases might simply not support a certain specVersion
> [INTERNAL] Clarify error message for invalid or unsupported specVersions

- lib/projectPreprocessor.js
- test/lib/projectPreprocessor.js
Resolves #166 
NPM dependencies which cannot be configured (via yaml or shim) are
considered invalid and should not be part of the final project tree.
> [FIX] ProjectPreprocessor: Fix dependency processing

- docs/Configuration.md
Documents https://github.com/SAP/ui5-builder/pull/254
> [INTERNAL] Configuration docs: Add builder resource excludes

- package-lock.json
- package.json
- test/lib/extensions.js
- test/lib/normalizer.js
- test/lib/projectPreprocessor.js
- test/lib/translators/npm.js
- test/lib/translators/static.js
Relevant changelogs:
https://github.com/avajs/ava/releases/tag/v1.0.1
https://github.com/avajs/ava/releases/tag/v2.0.0
Relevant changes:
- AVA now requires at least Node.js 8.9.4. We require only 8.5.
However, since this is a devDependency I guess we can live with that.
- t.throws() does not accept promises anymore. Use t.throwsAsync()
- Test titles now must be unique
> [INTERNAL] Bump ava to 2.0.0

- docs/Configuration.md
Got implemented with https://github.com/SAP/ui5-builder/pull/241
> [INTERNAL] Document cachebuster signatureType configuration

- lib/projectPreprocessor.js
- test/lib/projectPreprocessor.js
This lead to the wrong dependency being removed in some cases.
Credits to @nlunets
> [FIX] projectPreprocessor: Do not remove already removed dependencies

- docs/Configuration.md
Feature was implemented with https://github.com/SAP/ui5-builder/pull/241.
> [INTERNAL] Move Cachebuster config documentation to correct section

- package-lock.json
- package.json
- test/lib/extensions.js
- test/lib/projectPreprocessor.js
Changelog of this version: SAP/ui5-builder:CHANGELOG.md@v1.4.0
> [INTERNAL] Bump @ui5/builder from 1.3.3 to 1.4.0

- lib/projectPreprocessor.js
When using the static translator, the dependencies are not filled, however the applyShims method (amongst other), directly try to iterate over it.
So in case dependencies does not exist we create it with an empty array
> [INTERNAL] projectPreprocessor: Make sure project dependencies exists

- lib/translators/static.js
- test/lib/translators/static.js
Some of our code relies on project paths being absolute (see https://github.com/SAP/ui5-project/pull/236).
Therefore ensure that they are always absolute.
> [INTERNAL] Static translator: Ensure that all project paths are absolute

- docs/Configuration.md
- lib/projectPreprocessor.js
- test/lib/extensions.js
- test/lib/projectPreprocessor.js
The new 'theme-library' type requires spec version 1.1:
https://github.com/SAP/ui5-builder/pull/285
Also change wording of the error message for unsupported spec versions
and fix the referenced URL. This should make it clear that the used
version of the UI5 CLI might be outdated.
> [FEATURE] Add specification version 1.1

- lib/projectPreprocessor.js
- test/lib/extensions.js
- test/lib/projectPreprocessor.js
Projects in the tree that are not the root project may trigger a warning
log if they configure any of the following metadata flags:
- deprecated: true
- sapInternal: true
The latter may not trigger a warning if its parent project defines a
metadata flag "allowSapInternal: true".
> [FEATURE] projectPreprocessor: Log warning when using a deprecated or restricted dependency

- lib/projectPreprocessor.js
- lib/translators/ui5Framework.js
- test/lib/translators/ui5Framework.integration.js
- test/lib/translators/ui5Framework.js
Since the root project of a framework tree has already been processed,
do not apply its type and additional checks again. This is to prevent
duplicate logging of infos and warnings and to reduce the overhead of
formatting the project again.
> [INTERNAL] ui5Framework/projectPreprocessor: Do not process root project again

- lib/projectPreprocessor.js
- lib/translators/ui5Framework.js
- test/lib/extensions.js
- test/lib/projectPreprocessor.js
- test/lib/translators/ui5Framework.integration.js
- test/lib/translators/ui5Framework.js
Support for spec version 2.0 in
ui5Framework translator and projectPreprocessor.
> [FEATURE] Support for spec version 2.0

- test/fixtures/application.a/webapp/manifest.json
- test/fixtures/cyclic-deps/node_modules/application.cycle.a/webapp/manifest.json
- test/fixtures/cyclic-deps/node_modules/library.cycle.a/src/cycle/a/.library
- test/fixtures/cyclic-deps/node_modules/library.cycle.b/src/cycle/b/.library
- test/lib/extensions.js
- test/lib/projectPreprocessor.js
Tests are failing due to https://github.com/SAP/ui5-builder/pull/430
Adopt tests to provide necessary manifest.json files and expect the
corresponding namespace information.
> [INTERNAL] projectPreprocessor tests: Adopt to required namespaces

- lib/translators/ui5Framework.js
This might especially happen when the root project does not use
specVersion 2.0 and defines framework libraries.
The info log might then be confusing.
> [INTERNAL] ui5Framework: Don't log info when no libs are found

- lib/validation/ValidationError.js
- lib/validation/schema/specVersion/2.0/kind/project.json
- test/lib/extensions.js
- test/lib/validation/ValidationError.js
- test/lib/validation/schema/specVersion/2.0/kind/project/application.js
- test/lib/validation/schema/specVersion/2.0/kind/project/library.js
> [INTERNAL] Schema: Update error messages / fix framework schema

- lib/translators/npm.js
- lib/translators/ui5Framework.js
- test/lib/translators/ui5Framework.integration.js
Since projects are deduped by the projectPreprocessor, repeated
processing of a project that appears multiple times in the project tree
is done on the same object. This leads to issues like the
isFrameworkProject detecting previously added framework libraries as ...
"already added UI5 framework libraries", thus producing incorrect log
messages
The eventual result in projects where a reuse library defining UI5 dependencies has multiple occurrences in the tree is excessive logging like this:
```sh
info normalizer:translators:ui5Framework If project my.pony.collection contains a package.json in which it defines a dependency to the UI5 framework library @openui5/sap.f, this dependency should be removed.
info normalizer:translators:ui5Framework If project my.pony.collection contains a …
```
> [FIX] ui5Framework.mergeTrees: Do not process the same project multiple times

- package-lock.json
- package.json
There has been a lot of development in pacote since v9:
https://github.com/npm/pacote/compare/v9...latest
It seems that some things don't work as expected with the newer
releases, maybe because of newer transitive dependencies.
For once I got "invalid json response body" errors while fetching from
an internal registry. Then there's also #298. This change resolves both
issues (and possibly more we don't know of yet).
Resolves #298
> [FIX] package.json: Downgrade pacote from 11.1.4 to 9.5.12

- lib/ui5Framework/AbstractResolver.js
- test/lib/ui5framework/AbstractResolver.js
If the requested framework version is lower than what is the lowest
version currently available in the public npm registry, throw a more
precise error message if it can't be resolved.
> [INTERNAL] AbstractResolver: Throw more precise error when requested framework version is known to be unavailable

- lib/ui5Framework/Sapui5Resolver.js
The SAPUI5 distribution metadata package is missing dependency
information for all OpenUI5 libraries. Therefore we need to fallback to
requesting the dependency information from the registry (like it is
done in OpenUI5 projects).
> [FIX] Workaround missing dependency info for OpenUI5 packages in version 1.77.x

- lib/projectPreprocessor.js
- lib/validation/schema/specVersion/2.0.json
- lib/validation/schema/specVersion/2.0/kind/extension.json
- lib/validation/schema/specVersion/2.0/kind/extension/project-shim.json
- lib/validation/schema/specVersion/2.0/kind/extension/server-middleware.json
- lib/validation/schema/specVersion/2.0/kind/extension/task.json
- lib/validation/schema/specVersion/2.0/kind/project.json
- lib/validation/schema/specVersion/2.0/kind/project/application.json
- lib/validation/schema/specVersion/2.0/kind/project/library.json
- lib/validation/schema/specVersion/2.0/kind/project/module.json
- lib/validation/schema/specVersion/2.0/kind/project/theme-library.json
- lib/validation/schema/ui5.json
- package.json
- test/lib/extensions.js
- test/lib/validation/schema/__helper__/customConfiguration.js
- test/lib/validation/schema/__helper__/extension.js
- test/lib/validation/schema/__helper__/framework.js
- test/lib/validation/schema/__helper__/project.js
- test/lib/validation/schema/specVersion/2.0/kind/extension.js
- test/lib/validation/schema/specVersion/2.0/kind/extension/project-shim.js
- test/lib/validation/schema/specVersion/2.0/kind/extension/server-middleware.js
- test/lib/validation/schema/specVersion/2.0/kind/extension/task.js
- test/lib/validation/schema/specVersion/2.0/kind/project/application.js
- test/lib/validation/schema/specVersion/2.0/kind/project/library.js
- test/lib/validation/schema/specVersion/2.0/kind/project/module.js
- test/lib/validation/schema/specVersion/2.0/kind/project/theme-library.js
- test/lib/validation/schema/ui5.js
> [FEATURE] specVersion 2.1: Add support for "customConfiguration"

- lib/projectPreprocessor.js
- test/lib/projectPreprocessor.js
https://github.com/SAP/ui5-project/pull/308 only allowed the use of the
new spec version for extensions.
> [FIX] Allow the use of specVersion 2.1 for projects

- index.js
- jsdoc-plugin.js
- jsdoc.json
Lazy-loading breaks the automatic type definition detection from
TypeScript. Therefore we need to manually declare the exported types.
> [FIX] Node.js API: TypeScript type definition support

- lib/projectPreprocessor.js
- lib/translators/ui5Framework.js
- lib/validation/schema/specVersion/2.0.json
- lib/validation/schema/specVersion/2.0/kind/extension.json
- lib/validation/schema/specVersion/2.0/kind/extension/project-shim.json
- lib/validation/schema/specVersion/2.0/kind/extension/server-middleware.json
- lib/validation/schema/specVersion/2.0/kind/extension/task.json
- lib/validation/schema/specVersion/2.0/kind/project.json
- lib/validation/schema/specVersion/2.0/kind/project/application.json
- lib/validation/schema/specVersion/2.0/kind/project/library.json
- lib/validation/schema/specVersion/2.0/kind/project/module.json
- lib/validation/schema/specVersion/2.0/kind/project/theme-library.json
- lib/validation/schema/ui5.json
- test/lib/projectPreprocessor.js
- test/lib/validation/schema/__helper__/customConfiguration.js
- test/lib/validation/schema/__helper__/extension.js
- test/lib/validation/schema/__helper__/framework.js
- test/lib/validation/schema/__helper__/project.js
- test/lib/validation/schema/specVersion/2.0/kind/extension.js
- test/lib/validation/schema/specVersion/2.0/kind/extension/project-shim.js
- test/lib/validation/schema/specVersion/2.0/kind/project/application.js
- test/lib/validation/schema/specVersion/2.0/kind/project/library.js
- test/lib/validation/schema/specVersion/2.0/kind/project/module.js
- test/lib/validation/schema/specVersion/2.0/kind/project/theme-library.js
- test/lib/validation/schema/ui5.js
- Allows custom task extensions to use the new `taskUtil` API.
- No structural changes to the ui5.yaml schema
RFC: https://github.com/SAP/ui5-tooling/pull/243
> [FEATURE] specVersion 2.2

- lib/ui5Framework/AbstractResolver.js
- lib/ui5Framework/npm/Installer.js
- package.json
- test/lib/translators/ui5Framework.integration.js
- test/lib/ui5framework/npm/Installer.js
Start a package install into a dedicated staging directory. Only if
download and extraction have completed, rename the staging- to the
target directory.
If subsequent ui5Framework translator executions detect an existing
staging directory during installation of a package, this directory shall
be removed first to ensure a complete install.
Alternative approach to https://github.com/SAP/ui5-project/pull/382
Resolves https://github.com/SAP/ui5-tooling/issues/478
> [FIX] ui5Framework.Installer: Ensure atomic install process

- lib/ui5Framework/npm/Installer.js
- test/lib/ui5framework/npm/Installer.js
Renaming a directory might fail with an EPERM error on Windows if the
target already exists. Therefore we stop creating the target directory
before the rename (this was probably the main problem) and also ensure
that it does not exist for whatever other reasons.
Related: https://github.com/SAP/ui5-project/pull/389
Resolves: https://github.com/SAP/ui5-tooling/issues/487
> [FIX] ui5Framework.Installer: Ensure target directory does not exist before rename

- lib/translators/ui5Framework.js
- test/lib/translators/ui5Framework.js
Because they don't have any. Otherwise a
"Cannot read property 'name' of undefined" error will be thrown.
This can only occur when using the "ui5 tree --full" command without the
--dedupe option or directly via API.
> [FIX] ui5Framework: Don't access metadata of deduped projects

- lib/ui5Framework/npm/Installer.js
- test/lib/ui5framework/npm/Installer.js
Prevents initialization of pacote in cases where all packages are
already installed (very common).
Leads to ~100ms faster build of openui5-sample-app.
Before:
After 4198ef3:
After c676dd4:
> [INTERNAL] Installer: Lazy require registry

- lib/translators/static.js
- test/lib/translators/static.js
- Allow passing a tree object instead of reading a YAML file
- Path resolution should be based on the passed directory, not based on
the process cwd
JIRA: CPOUI5FOUNDATION-403
> [INTERNAL] static translator: Add "tree" option, fix path resolution

- lib/build/ProjectBuilder.js
- lib/build/TaskRunner.js
- lib/build/helpers/BuildContext.js
- lib/build/helpers/ProjectBuildContext.js
- lib/build/helpers/TaskUtil.js
- lib/build/helpers/createBuildManifest.js
- lib/graph/ProjectGraph.js
- test/lib/build/ProjectBuilder.js
- test/lib/build/TaskRunner.js
- test/lib/build/helpers/BuildContext.js
- test/lib/build/helpers/ProjectBuildContext.js
- test/lib/build/helpers/TaskUtil.js
TaskUtil seems to be more influenced by ui5-project. To make it easier
to test and change with ui5-project changes, move it to this repository.
This also further decouples ui5-project from ui5-builder.
Now, ui5-project only requires the task repository from ui5-builder.
Therefore add a new, private API to ProjectGraph, allowing injection of
the module by ui5-builder tests. This ensures that ui5-builder does not
accidentially tests its build with a different version of itself.
> [INTERNAL] Move TaskUtil class to ui5-project, allow injection of taskRepository

- lib/specifications/Specification.js
- lib/specifications/types/extensions/ServerMiddleware.js
- lib/specifications/types/extensions/Task.js
- test/lib/specifications/Specification.js
- test/lib/specifications/types/Module.js
- test/lib/specifications/types/extensions/ServerMiddleware.js
- test/lib/specifications/types/extensions/Task.js
During the migration of legacy projects (defining specVersion < 2), the
propertiesFileSourceEncoding configuration was always added, even though
it is only relevant for applications and libraries. This lead to
validation errors for legacy projects of type "module" or extensions.
> [FIX] Specification: Fix migration for legacy projects that are not applications or libraries

- lib/build/ProjectBuilder.js
- lib/graph/Module.js
- test/lib/build/ProjectBuilder.js
Function was renamed in TaskRunner but mock was not updated.
Enhanced ui5-builder integration tests to cover this:
https://github.com/SAP/ui5-builder/pull/779
> [FIX] ProjectBuilder: Fix verbose logging for already built projects

- .eslintrc.js
- package-lock.json
- package.json
- test/lib/build/ProjectBuilder.js
- test/lib/build/TaskRunner.js
- test/lib/build/definitions/application.js
- test/lib/build/definitions/library.js
- test/lib/build/definitions/module.js
- test/lib/build/definitions/themeLibrary.js
- test/lib/build/helpers/TaskUtil.js
- test/lib/generateProjectGraph.usingObject.js
- test/lib/graph/Module.js
- test/lib/graph/ProjectGraph.js
- test/lib/graph/ShimCollection.js
- test/lib/graph/helpers/ui5Framework.integration.js
- test/lib/graph/projectGraphBuilder.js
- test/lib/specifications/ComponentProject.js
- test/lib/specifications/types/Application.js
- test/lib/specifications/types/Library.js
- test/lib/specifications/types/ThemeLibrary.js
- test/lib/specifications/types/extensions/ServerMiddleware.js
- test/lib/specifications/types/extensions/Task.js
- test/lib/ui5framework/AbstractResolver.js
- test/lib/ui5framework/npm/Installer.js
Introducing [eslint-plugin-ava](https://github.com/avajs/eslint-plugin-ava/) to avoid common pitfalls when writing powerful ava tests.
- Add plugin to eslint config and package.json
- Restructure current code base to latest recommendations
> [INTERNAL] use eslint-plugin-ava and cleanup test-suite

- test/lib/specifications/types/Application.js
- test/lib/specifications/types/Library.js
Node 19 has a new error message for invalid JSON. Instead of
"Unexpected token o in JSON at position 1" it now reads
"Unexpected token 'o', "no json" is not valid JSON"
> [INTERNAL] Invalid JSON: Fix unit tests for Node 19

- lib/build/helpers/TaskUtil.js
- test/lib/build/helpers/TaskUtil.js
Follow-up of https://github.com/SAP/ui5-project/pull/514 where this method was somehow missed
> [INTERNAL] TaskUtil: Provide resourceFactory#createReaderCollection

- lib/ui5Framework/npm/Installer.js
- package-lock.json
- package.json
- test/lib/graph/helpers/ui5Framework.integration.js
- test/lib/ui5framework/npm/Installer.js
The recursive option is available since Node v10.12, which makes the
use of thirdparty packages obsolete for most use cases.
> [INTERNAL] Use native fs.mkdir instead of mkdirp

- lib/build/TaskRunner.js
- lib/build/helpers/TaskUtil.js
- test/lib/build/helpers/TaskUtil.js
For custom task, this will return a Specification Version-dependent
(=compatible) interface of the Project instance a Resource is associated
with.
This was already described in RFC12[1] but not part of the initial
implementation of TaskUtil#getProject.
[1] https://github.com/SAP/ui5-tooling/pull/664
> [INTERNAL] TaskUtil#getProject: Retrieve Project for a given Resource

- lib/build/ProjectBuilder.js
- lib/build/TaskRunner.js
- lib/build/helpers/BuildContext.js
- lib/build/helpers/ProjectBuildContext.js
- lib/graph/ProjectGraph.js
- lib/specifications/Project.js
- lib/specifications/types/extensions/Task.js
- test/fixtures/extension.a.esm/lib/extensionModule.js
- test/fixtures/extension.a/lib/extensionModule.js
- test/lib/build/ProjectBuilder.js
- test/lib/build/TaskRunner.js
- test/lib/build/helpers/BuildContext.js
- test/lib/build/helpers/ProjectBuildContext.js
- test/lib/graph/ProjectGraph.js
- test/lib/specifications/Project.js
- test/lib/specifications/types/extensions/ServerMiddleware.js
- test/lib/specifications/types/extensions/Task.js
* Move requiresBuild() logic from TaskRunner to ProjectBuildContext
* This likely needs to be moved into a module of its own at some
point. For now, TaskRunner was the wrong place. If a project does
not need to be built, there is no need to instantiate a TaskRunner
in the first place. This is now implemented.
* TaskRunner can now compile a list of all direct project dependencies
required by the set of tasks that it will execute for the given build
options.
* Custom tasks defining specVersion >= 3.0 can now provide a
'determineRequiredDependencies' callback to define which dependencies
they require access to.
JIRA: CPOUI5FOUNDATION-568
> [INTERNAL] Refactor requires build/requires dependencies determination

- lib/graph/ProjectGraph.js
- lib/graph/helpers/ui5Framework.js
- lib/graph/projectGraphBuilder.js
- test/lib/graph/ProjectGraph.js
- test/lib/graph/helpers/ui5Framework.integration.js
- test/lib/graph/helpers/ui5Framework.js
- test/lib/graph/projectGraphBuilder.js
* Also fix a bug which caused optional framework dependencies to not be
resolved
* Do not log deprecation warnings for projects named "testsuite" (fixed
this for projectGraphBuilder)
* (separate commit) ProjectGraph: Cleanup resolved optional dependencies
>  [INTERNAL] ui5Framework: Log warning for deprecated and internal libs

- lib/build/ProjectBuilder.js
- lib/build/TaskRunner.js
- lib/build/helpers/createBuildManifest.js
- lib/graph/ProjectGraph.js
- test/lib/build/ProjectBuilder.js
- test/lib/build/TaskRunner.js
- test/lib/build/helpers/createBuildManifest.integration.js
- test/lib/build/helpers/createBuildManifest.js
- test/lib/graph/ProjectGraph.js
* Move requiresBuild() from TaskRunner to ProjectBuildContext
* This likely needs to be moved into a module of its own at some
point. For now, TaskRunner was the wrong place. If a project does
not need to be built, there is no need to instantiate a TaskRunner
in the first place. This is now implemented.
* TaskRunner can now compile a list of all direct project dependencies
required by the set of tasks that it will execute for the given build
options.
* Custom tasks defining specVersion >= 3.0 can now provide a
'determineRequiredDependencies' callback to define which dependencies
they require access to.
> [INTERNAL] Use new taskRepository API

- lib/build/ProjectBuilder.js
- lib/build/TaskRunner.js
- lib/build/helpers/composeProjectList.js
- lib/graph/ProjectGraph.js
- test/lib/build/ProjectBuilder.js
- test/lib/build/TaskRunner.js
- test/lib/graph/ProjectGraph.js
- test/lib/graph/helpers/ui5Framework.js
Refactor some methods based on current usage.
* **Internal:** Use Maps and Sets instead of objects and arrays
* Rename several methods
* **Traversal callbacks:** Provide array of dependency names instead of a
getDependency() function. Most consumers only need the names.
Corresponding projects can be easily retrieved via getProject()
* **Traversal callbacks:** Callback can be synchronous. Before, we required
a promise to be returned. Many consumers actually do not need to
perform async tasks
* Add a method for retrieving the names of all projects in the graph.
This is a common requirement
* Add a method for retrieving the number of projects in the graph.
This is also a common requirement
* **join:** Fix taking over optional dependencies and correspoinding flag
* **addProject:** Remove …
> [INTERNAL] ProjectGraph: Refactor API

- lib/build/helpers/BuildContext.js
- test/lib/build/helpers/BuildContext.js
Use-cases are unclear, so do not allow this for the time being.
> [INTERNAL] BuildContext: Disallow build-manifest creation for self-conftained builds

- lib/build/ProjectBuilder.js
- lib/build/TaskRunner.js
- lib/build/helpers/BuildContext.js
- lib/build/helpers/ProjectBuildContext.js
- test/lib/build/ProjectBuilder.js
- test/lib/build/TaskRunner.js
- test/lib/build/helpers/BuildContext.js
- test/lib/build/helpers/ProjectBuildContext.js
* Use template literals instead of placeholders.
* Replace GroupLogger with standard Logger instance in ProjectBuilder
* Pass standard Logger instead of GroupLogger to custom tasks
This is in prepration for @ui5/logger changes as per
https://github.com/SAP/ui5-logger/pull/353
> [INTERNAL] Refactor log-calls

- lib/build/TaskRunner.js
- test/lib/build/TaskRunner.js
Always provide a 'dependencies'-reader to custom tasks, unless they
define Specification Version >=3.0 and do not provide a
determineRequiredDependencies callback.
The latter being an indicator that either dependencies are really not
required by the task or that the concept of the callback is not yet
known or applied incorrectly. By not providing any dependencies reader
in this case, the task will face an exception if access to the reader is
still attempted, for example via 'dependencies.byGlob()' (=> 'byGlob of
undefined').
At the same time, tasks implementing the callback but not requesting any
dependencies will receive an empty 'dependencies'-reader. This can ease
the implementation efforts in the task.
Resolves https://github.com/SAP/ui5-tooling/issues/732
> [INTERNAL] TaskRunner: Custom Tasks receive 'dependencies' reader in most cases

- lib/build/definitions/library.js
- lib/build/definitions/themeLibrary.js
- test/lib/build/TaskRunner.js
- test/lib/build/definitions/library.js
- test/lib/build/definitions/themeLibrary.js
The generateThemeDesignerResources task is currently only relevant for
framework libraries as those libraries are supported by SAP Theme Designer.
Other libraries are not expected to require the task, so it is skipped.
> [BREAKING] Run 'generateThemeDesignerResources' only on framework libs

- lib/build/helpers/TaskUtil.js
- lib/specifications/Project.js
- lib/specifications/types/Application.js
- lib/specifications/types/Library.js
- lib/specifications/types/Module.js
- lib/specifications/types/ThemeLibrary.js
- test/lib/build/helpers/TaskUtil.js
The method will also be provided through TaskUtil and MiddlewareUtil.
This should help use cases like in the ui5-middleware-fe-mockserver:
https://github.com/SAP/open-ux-odata/blob/main/packages/ui5-middleware-fe-mockserver/src/index.ts#L10
> [INTERNAL] specification/Project: Make getSourcePath method public

- lib/specifications/Specification.js
- lib/validation/schema/specVersion/kind/extension.json
- lib/validation/schema/specVersion/kind/extension/project-shim.json
- lib/validation/schema/specVersion/kind/extension/server-middleware.json
- lib/validation/schema/specVersion/kind/extension/task.json
- lib/validation/schema/specVersion/kind/project.json
- lib/validation/schema/specVersion/kind/project/application.json
- lib/validation/schema/specVersion/kind/project/library.json
- lib/validation/schema/specVersion/kind/project/module.json
- lib/validation/schema/specVersion/kind/project/theme-library.json
- test/lib/specifications/Specification.js
- test/lib/validation/schema/__helper__/extension.js
- test/lib/validation/schema/__helper__/project.js
- test/lib/validation/schema/specVersion/kind/extension.js
- test/lib/validation/schema/specVersion/kind/extension/project-shim.js
- test/lib/validation/schema/specVersion/kind/extension/server-middleware.js
- test/lib/validation/schema/specVersion/kind/extension/task.js
- test/lib/validation/schema/specVersion/kind/project.js
- test/lib/validation/schema/specVersion/kind/project/application.js
- test/lib/validation/schema/specVersion/kind/project/library.js
- test/lib/validation/schema/specVersion/kind/project/module.js
- test/lib/validation/schema/specVersion/kind/project/theme-library.js
As proposed in chapter 6 of RFC0012([1]), restrict the 'name' property for
projects and extensions defining specification version 3.0 and later.
For projects and extensions defining specVersion 3.0 and later, the
metadata.name property must satisfy the following conditions:
* Must be at least 3 characters long
* Must be no longer than 50 characters
* Must only contain lowercase characters
* Must only contain alphanumeric characters, dash, underscore, dot
- Exception: `@` and `/` are allowed at certain positions as
explained below
* Must start with an alphabetic character or an `@`-character
* If a name starts with an `@`-character, it must contain exactly one
forward-slash `/`
- This is aligned with the npm concept for package scopes
- e.g. `@org/lib.name`
For details, …
> [BREAKING] Schema: Restrict metadata.name for specVersion >= 3.0

- lib/ui5Framework/npm/Registry.js
@ui5/logger used to be based on 'npmlog', which allowed us to pass the
same instance to pacote. Since this is no longer the case, remove the
respective code.
> [FIX] Registry: Do not use custom logger for pacote

- lib/graph/helpers/ui5Framework.js
- test/lib/graph/helpers/ui5Framework.js
If the current root project is a framework project (identified by the scope in the package.json name), allow processing of it's framework dependencies by the ui5Framework helper module. Other framework projects in the graph are still ignored.
Framework dependencies of non-framework projects are always processed. Framework dependencies of framework projects have always been ignored. With this change, framework dependencies of the root project are always processed, no matter whether it's a framework projects or not.
This allows framework developers to retrieve all required dependencies in a given version. The version is either defined in the ui5.yaml (not recommended) or via the --framework-version CLI parameter.
If no version is specified, all required framework dependencies must be part …
> [INTERNAL] Allow framework projects use of framework resolver

- lib/validation/schema/specVersion/kind/extension.json
- lib/validation/schema/specVersion/kind/project.json
- lib/validation/schema/ui5-workspace.json
- test/lib/validation/schema/specVersion/kind/extension.js
- test/lib/validation/schema/specVersion/kind/extension/project-shim.js
- test/lib/validation/schema/specVersion/kind/extension/server-middleware.js
- test/lib/validation/schema/specVersion/kind/extension/task.js
- test/lib/validation/schema/specVersion/kind/project.js
- test/lib/validation/schema/specVersion/kind/project/application.js
- test/lib/validation/schema/specVersion/kind/project/library.js
- test/lib/validation/schema/specVersion/kind/project/module.js
- test/lib/validation/schema/specVersion/kind/project/theme-library.js
- test/lib/validation/schema/ui5-workspace.js
As discussed, raise the limit since we already encountered projects
using more than 60 characters for their name.
> [INTERNAL] Schema: Allow metadata.name to be up to 80 characters long

- lib/build/ProjectBuilder.js
- lib/specifications/ComponentProject.js
- lib/specifications/Project.js
- lib/specifications/types/Application.js
- lib/specifications/types/Library.js
- lib/specifications/types/Module.js
- lib/specifications/types/ThemeLibrary.js
- test/lib/build/ProjectBuilder.js
- test/lib/specifications/types/Application.js
- test/lib/specifications/types/Library.js
- test/lib/specifications/types/Module.js
- test/lib/specifications/types/ThemeLibrary.js
Introduce new style `dist` to reflect the standard build output
structure which can be used with any HTTP server. It is identical to the
`runtime` style, but also applies any configured [builder resource
excludes](https://sap.github.io/ui5-tooling/stable/pages/Configuration/#exclude-resources).
ProjectBuilder now uses style 'dist' instead of 'runtime'.
Fixes https://github.com/SAP/ui5-tooling/issues/779
> [FIX] Project#getReader: Do not apply builder resource excludes for style 'runtime'

- lib/graph/graph.js
- test/lib/graph/graph.integration.js
- test/lib/graph/graph.js
- test/lib/graph/graphFromObject.js
- test/lib/graph/graphFromStaticFile.js
This should restore the v2 behavior where referencing a ui5.yaml file
via the '--config' CLI parameter can always be done with a path relative
to the directory the CLI has been invoked in.
v3 used to pass the relative path to graph/Module which would resolve it
against the module's root path (typically the location of the
package.json) using @ui5/fs.
This can be unexpected, for example if the CLI is invoked in a
subdirectory of the module. Also, referencing configuration files
outside of the module (e.g. "../ui5.yaml") was no longer possible.
> [FIX] graph: Always resolve rootConfigPath to CWD

- lib/graph/projectGraphBuilder.js
- test/lib/graph/graphFromObject.js
- test/lib/graph/helpers/ui5Framework.integration.js
- test/lib/graph/projectGraphBuilder.js
The same module will be processed every time another module depends on
it. This change ensures that any extensions contained in the module will
only be applied once and only if the dependency is non-optional or if
the parent project is the root project.
Fixes https://github.com/SAP/ui5-tooling/issues/777
> [FIX] projectGraphBuilder: Apply extensions of the same module only once

- lib/specifications/types/Library.js
- test/lib/specifications/types/Library.js
Copyright determination should not enforce the existence of a .library
file.
This restores the v2 behavior where a failed copyright determination did
not cause an exception:
https://github.com/SAP/ui5-builder/blob/5846c4dfe3bb45e8e61b0458520787211438d872/lib/types/library/LibraryFormatter.js#L56-L58
> [FIX] Library: Do not throw for missing .library file

- lib/build/helpers/TaskUtil.js
- lib/specifications/Project.js
- test/lib/build/helpers/TaskUtil.js
This was missed to add to the initial 3.0.0 release
> [FIX] TaskUtil: Provide framework configuration getters to custom tasks

- lib/specifications/ComponentProject.js
- test/lib/specifications/types/Application.js
- test/lib/specifications/types/Library.js
- test/lib/specifications/types/Module.js
- test/lib/specifications/types/ThemeLibrary.js
This resolves a regression caused by
https://github.com/SAP/ui5-project/pull/574 where the application of
builder resource-exclude configuration was moved from the low-level
_getSourceReader/_getTestReader methods to the high-level getReader API.
However, it was missed to also adapt the high-level getWorkspace API in
the same manner.
This caused the created workspace reader/writer to ignore any exclude
configuration as reported in
https://github.com/SAP/ui5-tooling/issues/784#issuecomment-1433625146
> [FIX] ComponentProject#getWorkspace: Apply builder resource excludes

- lib/ui5Framework/AbstractResolver.js
- test/lib/ui5framework/AbstractResolver.js
This fix resolves https://github.com/SAP/ui5-tooling/issues/796
The core issue is that in particular CI environments `os.homedir()` might be enforced to return a relative path.
We rely only on absolute paths in the tooling, so we'd need to ensure this.
> [FIX] Resolve properly absolute path for ui5HomeDir

- lib/graph/Workspace.js
- lib/specifications/Project.js
- lib/specifications/Specification.js
- test/lib/graph/Workspace.js
- test/lib/specifications/Specification.js
Required for https://github.com/SAP/ui5-project/pull/589
> [FEATURE] Workspace: Add getModules method / Specification: Add getId method

- lib/graph/helpers/ui5Framework.js
- lib/ui5Framework/AbstractResolver.js
- lib/ui5Framework/Openui5Resolver.js
- lib/ui5Framework/Sapui5MavenSnapshotResolver.js
- lib/ui5Framework/Sapui5Resolver.js
- lib/ui5Framework/maven/Installer.js
- lib/ui5Framework/maven/Registry.js
- lib/ui5Framework/npm/Installer.js
- lib/ui5Framework/npm/Registry.js
- test/lib/graph/helpers/ui5Framework.integration.js
- test/lib/graph/helpers/ui5Framework.js
- test/lib/ui5framework/AbstractResolver.js
- test/lib/ui5framework/Sapui5MavenSnapshotResolver.js
- test/lib/ui5framework/maven/Installer.js
- test/lib/ui5framework/maven/Registry.js
~~This is just a rebase with `main` of [Enable snapshot consumption from Maven repository #569](https://github.com/SAP/ui5-project/pull/478). The original change had conflicts with the [workspace implementation](https://github.com/SAP/ui5-project/pull/494).~~
Implementation of snapshot consumption from Maven repository. This is the final implementation and is the continuation work from the base change: https://github.com/SAP/ui5-project/pull/478
~~The change also implements the RFC for a [Configuration](https://github.com/SAP/ui5-tooling/blob/rfc-configuration/rfcs/0013-configuration.md)~~
The configuration part has been moved into a separate change: https://github.com/SAP/ui5-project/pull/575
JIRA: CPOUI5FOUNDATION-581
> [FEATURE] Enable snapshot consumption from Maven repository

- lib/ui5Framework/AbstractResolver.js
- test/lib/ui5framework/AbstractResolver.js
By setting environment variable 'UI5_PROJECT_USE_FRAMEWORK_SOURCES' to
any value, resolvers will be forced to always download the sources of
framework dependencies rather than pre-built versions.
Currently this only really affects the Sapui5MavenSnapshotResolver,
being the only resolver capable of downloading pre-built packages as of
today.
JIRA: CPOUI5FOUNDATION-657
> [INTERNAL] AbstractResolver: Add env var to enforce usage of framework lib sources

- lib/ui5Framework/Sapui5MavenSnapshotResolver.js
- test/lib/ui5framework/Sapui5MavenSnapshotResolver.js
"UI5_MAVEN_SNAPSHOT_ENDPOINT" => "UI5_MAVEN_SNAPSHOT_ENDPOINT_URL"
Also always prefer it over the API parameter.
> [INTERNAL] Sapui5MavenSnapshotResolver: Rename endpoint URL env var

- lib/ui5Framework/npm/Registry.js
- test/lib/ui5framework/npm/Registry.js
This commit fixes a regression caused via https://github.com/SAP/ui5-project/pull/579
The proxy functionality relies on the agent option so it must not be
disabled when using a proxy.
This again enables proxy support but doesn't solve potential
"Socket Timeout" issues that might also appear when using a proxy
(see https://github.com/SAP/ui5-project/pull/579).
The https-proxy option is now also taken into account, which didn't work
before due to missing normalization from https-proxy to httpsProxy.
Fixes: https://github.com/SAP/ui5-tooling/issues/822
> [FIX] ui5Framework: Respect npm proxy configuration to fetch libraries

- lib/graph/projectGraphBuilder.js
- test/lib/graph/projectGraphBuilder.js
If a visited module did not resolve to any specification (project or
extensions), try recreating the module when visiting it again from a
different parent.
Resolves https://github.com/SAP/ui5-tooling/issues/807
This is an alternative to https://github.com/SAP/ui5-project/pull/611
This change might have a greater impact on performance since er might
recreate modules that are not relevant to UI5 Tooling more than once if
they are listed multiple times in the dependency tree.
Before this change, such modules where only visited once.
> [FIX] projectGraphBuilder: Add module cache invalidation

- lib/graph/Workspace.js
- test/fixtures/collection.b/sub-empty/.keep
If a dynamic npm workspaces[1] configuration resolves to a directory
lacking a package.json file, ignore that module silently.
This can happen when using a pattern like "packages/*" in the workspaces
configuration, and then deleting a package. In case files on .gitignore
remain in the directory for some users, the physical directory is not
removed by git. This lead to issues for UI5 Tooling, trying to use the
empty directory and throwing because of the lacking package.json.
With this change, an error is only thrown if the module path is
explicitly configured (no pattern).
[1] https://docs.npmjs.com/cli/v9/using-npm/workspaces?v=true
> [FIX] Workspace: Ignore empty npm workspace modules

- lib/graph/helpers/ui5Framework.js
- test/lib/graph/helpers/ui5Framework.integration.js
- test/lib/graph/helpers/ui5Framework.js
This is a v3 regression. Optional dependencies of the root project
should always be enforced (just like development dependencies).
Instead, ui5Framework would correctly install them, but then declared the
dependency in the graph as 'optional'. Which meant the dependency would
only be enforced if another dependency would define a non-optional
dependency to it.
BCP: 2380060321
> [FIX] ui5Framework: Treat 'optional' dependencies of root project as non-optional

- lib/ui5Framework/maven/Registry.js
Applying the fix from https://github.com/SAP/ui5-project/pull/579 in the Maven Registry module
> [FIX] maven/Registry: Prevent socket timeouts when installing framework libraries

- lib/ui5Framework/Sapui5MavenSnapshotResolver.js
- lib/ui5Framework/maven/Installer.js
- test/lib/ui5framework/Sapui5MavenSnapshotResolver.js
- test/lib/ui5framework/maven/Installer.js
> [FEATURE] Sapui5MavenSnapshotResolver: Use npm-dist.zip artifact for 1.116.0 and later

- lib/ui5Framework/npm/Registry.js
- package-lock.json
- package.json
- test/lib/graph/helpers/ui5Framework.integration.js
- test/lib/ui5framework/npm/Registry.js
fixes: https://github.com/SAP/ui5-tooling/issues/786
JIRA: CPOUI5FOUNDATION-631
> [INTERNAL] Migrate from libnpmconfig to @npmcli/config

- lib/graph/Module.js
- lib/graph/graph.js
Minor fix of outdated JSDoc links. Plus added a new link to the
documentation chapter added in
https://github.com/SAP/ui5-tooling/pull/843
> [INTERNAL] graph: Fix JSDoc links

- lib/specifications/types/Application.js
- test/lib/specifications/types/Application.js
This fixes a regression presumably present since ui5-project v3.0.0,
which prevented proper fallback to manifest.appdescr_variant in case no
manifest.json is found in the project.
> [FIX] Application: Fallback to manifest.appdescr_variant if manifest.json is not found

- lib/config/Configuration.js
- lib/graph/helpers/ui5Framework.js
- test/lib/config/Configuration.js
- test/lib/graph/helpers/ui5Framework.js
- test/lib/ui5framework/Sapui5MavenSnapshotResolver.js
> [FEATURE] Allow to configure location of UI5 home directory

- lib/config/Configuration.js
- lib/graph/helpers/ui5Framework.js
- test/lib/config/Configuration.js
- test/lib/graph/helpers/ui5Framework.integration.js
- test/lib/graph/helpers/ui5Framework.js
The UI5 data directory (previously called UI5 home directory) should
always be resolved relative to the project directory, which is where
the package.json file is located at.
This change also adds a list of options to the Configuration class to be
used by the CLI config command to allow all available config options to
be set or retrieved.
Follow-up of https://github.com/SAP/ui5-project/pull/635
JIRA: CPOUI5FOUNDATION-715
JIRA: CPOUI5FOUNDATION-716
> [FIX] Resolve UI5 data directory relative to project

- lib/ui5Framework/AbstractResolver.js
- test/lib/ui5framework/AbstractResolver.js
For example 'ui5 use 1' should resolve to the latest 1.x.x version
> [FEATURE] AbstractResolver: Resolve version ranges specifying major version only

- lib/ui5Framework/npm/Registry.js
- test/lib/graph/helpers/ui5Framework.integration.js
- test/lib/ui5framework/npm/Registry.js
Fixes regression from https://github.com/SAP/ui5-project/pull/618
> [FIX] pacote: Use npm cache within UI5 data dir

- lib/graph/helpers/ui5Framework.js
- test/lib/graph/helpers/ui5Framework.js
Also moves check for framework libraries to earlier point as further
steps such as choosing a resolver and calling resolveVersion are only
needed when libraries are referenced.
This aligns the behavior with not having a framework configuration at
all but still passing "versionOverride" which is then also not
resolved/checked for correctness.
> [FIX] Ensure usage of provided UI5 data dir

- lib/ui5Framework/AbstractResolver.js
- lib/ui5Framework/Openui5Resolver.js
- lib/ui5Framework/Sapui5Resolver.js
- lib/ui5Framework/npm/Installer.js
- test/lib/graph/helpers/ui5Framework.integration.js
- test/lib/ui5framework/AbstractResolver.js
- test/lib/ui5framework/Openui5Resolver.integration.js
- test/lib/ui5framework/Openui5Resolver.js
- test/lib/ui5framework/Sapui5MavenSnapshotResolver.integration.js
- test/lib/ui5framework/Sapui5Resolver.integration.js
- test/lib/ui5framework/Sapui5Resolver.js
The framework version resolution now supports all valid node semver
ranges and uses tags from the corresponding registry for version
resolution (not supported for Sapui5MavenSnapshotResolver).
JIRA: CPOUI5FOUNDATION-722
> [FEATURE] Resolvers: Allow ranges / npm tags for version resolution

- azure-pipelines.yml
Reverts SAP/ui5-project#657
Node 20.6.1 has been released.
> [INTERNAL] Revert "Azure Pipelines: Switch back to Node 20.5.x"

- lib/build/TaskRunner.js
- lib/build/definitions/application.js
- lib/build/definitions/library.js
- lib/build/definitions/themeLibrary.js
- test/lib/build/TaskRunner.js
- test/lib/build/definitions/application.js
- test/lib/build/definitions/library.js
- test/lib/build/definitions/themeLibrary.js
This change allows custom tasks to subscribe to any standard task, even disabled ones, ensuring custom tasks' execution and the correct order.
Background information:
When transitioning a project from V2 to V3, we often need to adjust the before/after task assignments for custom tasks due to the removal of the `uglify` task. The new `minify` task now runs earlier than the previous `uglify` task.
Developers typically used `uglify` as the last enabled standard task to subscribe to. 
You can find updated documentation here: https://github.com/SAP/ui5-tooling/pull/874
JIRA: CPOUI5FOUNDATION-724
> [FIX] Allow usage of after/before task assignment for all standard tasks

- lib/ui5Framework/maven/Registry.js
- lib/ui5Framework/npm/Registry.js
- test/lib/ui5framework/npm/Registry.js
This ultimately reverts https://github.com/SAP/ui5-project/pull/579
since make-fetch-happen dropped agentkeepalive in favor of @npmcli/agent
which in our tests did not show the problematic behavior.
Depends on: https://github.com/SAP/ui5-project/pull/643
> [INTERNAL] npm/maven Registry: Restore use of shared keep-alive agents

- .gitattributes
The GitHub file finder feature assumes "build/" directories contain
generated code and therefore ignores them.
This change configures lib/build/* to not be treated as generated code.
Resources:
* https://github.blog/changelog/2022-07-28-file-finder-customize-default-exclusions/
* https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github
GitHub Support Ticket: #2427846
> [INTERNAL] GitHub: Include lib/build/* in file finder

- lib/build/ProjectBuilder.js
- lib/build/helpers/BuildContext.js
- lib/build/helpers/ProjectBuildContext.js
- lib/build/helpers/TaskUtil.js
- test/lib/build/ProjectBuilder.js
- test/lib/build/helpers/BuildContext.js
JIRA: CPOUI5FOUNDATION-751
\@ui5/builder PR that depends on this change: https://github.com/SAP/ui5-builder/pull/953
When cleaning up after tasks run, it can happen in couple cases:
- When the project is build
- When there's a SIGTERM signal
- (Maybe) on some error
We need to be able to distinguish between those cases as in some places we rely on graceful termination and cleanup. Especially, after the project has been build successfully. On the other hand when the user presses `Ctrl + C`, for example, we need to enforce the termination.
This cahnge provides this context.
> [FEATURE] TaskUtil: Add 'force' flag to cleanup task callback

- .gitattributes
File finder still won't find files in lib/build/ dir, so GitHub support
suggested adding these lines for further investigation.
Follow up to https://github.com/SAP/ui5-project/pull/679
GitHub Support Ticket: #2427846
> [INTERNAL] GitHub: Include lib/** in file finder

- .gitattributes
GitHub Support suggests to add this line since thir default
configuration uses the pattern "build/**" too.
Follow up to #680
GitHub Support Ticket: #2427846
> [INTERNAL] GitHub: Include build/** in file finder

- lib/build/ProjectBuilder.js
- lib/build/helpers/BuildContext.js
- lib/build/helpers/ProjectBuilderOutputStyle.js
- lib/graph/ProjectGraph.js
- test/lib/build/ProjectBuilder.js
- test/lib/build/helpers/BuildContext.js
- test/lib/build/helpers/ProjectBuildContext.js
New option `outputStyle`. Whether to omit the `/resources/<namespace>` directory structure in the build output.
Resolves https://github.com/SAP/ui5-tooling/issues/507
> [FEATURE] ProjectBuilder: Add `outputStyle` option to request flat build output

- lib/graph/graph.js
- test/lib/graph/graph.js
Set default workspaceName to "default" for API usage (https://github.com/SAP/ui5-project/pull/586)
JIRA: CPOUI5FOUNDATION-802
Relates to: https://github.com/SAP/ui5-tooling/issues/701
> [BREAKING] Set default workspaceName to "default" for API usage

- lib/graph/helpers/ui5Framework.js
- lib/ui5Framework/AbstractInstaller.js
- lib/ui5Framework/AbstractResolver.js
- lib/ui5Framework/Openui5Resolver.js
- lib/ui5Framework/Sapui5MavenSnapshotResolver.js
- lib/ui5Framework/Sapui5Resolver.js
- lib/ui5Framework/maven/Installer.js
- lib/ui5Framework/npm/Installer.js
- test/lib/graph/helpers/ui5Framework.js
- test/lib/ui5framework/AbstractResolver.js
- test/lib/ui5framework/Openui5Resolver.integration.js
- test/lib/ui5framework/Openui5Resolver.js
- test/lib/ui5framework/Sapui5MavenSnapshotResolver.js
- test/lib/ui5framework/Sapui5Resolver.integration.js
- test/lib/ui5framework/Sapui5Resolver.js
- test/lib/ui5framework/maven/Installer.js
- test/lib/ui5framework/npm/Installer.js
Installers and Resolvers' argument `ui5HomeDir` is now renamed to `ui5DataDir`
JIRA: CPOUI5FOUNDATION-802
Relates to: https://github.com/SAP/ui5-tooling/issues/701
> [BREAKING] Rename ui5HomeDir to ui5DataDir in APIs

- lib/graph/ProjectGraph.js
- package-lock.json
- package.json
This decoupling allows the use of @ui5/project without having to install
@ui5/builder with all its transitive dependencies in cases where no
build functionality is required. An example for that is UI5 linter.
Consumers of the Node.js API that make use of the `ProjectGraph#build` method need to declare a dependency to `@ui5/builder` in their respective package.json. The package manager should ensure that the version fullfills the range specified in the package.json of `@ui5/project`.
JIRA: CPOUI5FOUNDATION-854
> [BREAKING] Make '@ui5/builder' an optional peerDependency

- package.json
This is required for local development. Otherwise npm would error out
since the local 4.x version does not satisfy the ^3 range.
> [INTERNAL] Enhance range of @ui5/builder peer dependency

- lib/build/definitions/library.js
- test/lib/build/definitions/library.js
The framework intends to move the buildtime timestamp from Global.js to
Core.js. With this change, UI5 Tooling will always scan both files for
the placeholder and process it accordingly.
JIRA: CPOUI5FRAMEWORK-647
> [INTERNAL] library: Replace buildtime timestamp in sap/ui/core/Core.js

- package.json
The range for v3.x had to be included for technical reasons before the first v4 release but it was not intended to be defined that way.
> [DEPENDENCY] Fix @ui5/builder peerDependency range

- lib/validation/schema/specVersion/kind/project.json
The default value in the schema was not aligned with the actual default
value in the code.
Starting with v4, the default values are applied to the bundle config,
which is why it now started to matter.
> [FIX] decorateBootstrapModule should default to "false"
